[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.8
blur = true
startup_mode = "Maximized"
resize_increments = true

[font]
normal.family = "FiraCode Nerd Font Mono"
size = 14

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
