tap "homebrew/bundle"
brew "mas"
cask "fractal-bot"
cask "godot"
cask "ledger-live"
cask "raycast"
cask "tailscale"
cask "zed"
mas "Flighty", id: 1358823008
mas "GarageBand", id: 682658836
mas "JSONPeep", id: 1458969831
mas "Steam Link", id: 1246969117
